
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml6app
spec:
  selector:
    matchLabels:
      app: ml6app
  replicas: 1
  template:
    metadata:
      labels:
        app: ml6app
    spec:
      containers:
      - name: ml6app
        image: ml6app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080