apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml6app
  labels:
    name: ml6app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml6app
  template:
    metadata:
      labels:
        app: ml6app
    spec:
      containers:
      - name: ml6app
        image: gcr.io/ml6-application/flask-app:v1
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080