apiVersion: v1
kind: Service
metadata:
  name: ml6app
spec:
  selector:
    app: ml6app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: ml6app/v1
kind: Deployment
metadata:
  name: ml6app
spec:
  selector:
    matchLabels:
      app: ml6app
  replicas: 2
  template:
    metadata:
      labels:
        app: ml6app
    spec:
      containers:
      - name: ml6app
        image: ml6app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000